
name: Release
on:
  workflow_dispatch:
  schedule:
    - cron: "30 4 * * *"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Compare latest tags and set variables
        run: |
          upstreamLatestTag=$(curl https://api.github.com/repos/Loyalsoldier/domain-list-custom/releases/latest | grep "tag_name" | cut -d\" -f4 | cut -c 1-12)
          thisLatestTag=$(curl https://api.github.com/repos/${{ github.repository }}/releases/latest | grep "tag_name" | cut -d\" -f4)
          if [[ $upstreamLatestTag != $thisLatestTag ]]; then
            echo "NeedToSync=true" >> $GITHUB_ENV
          fi
          echo "RELEASE_NAME=$upstreamLatestTag" >> $GITHUB_ENV
          echo "TAG_NAME=$upstreamLatestTag" >> $GITHUB_ENV

      - name: log
        if: ${{ env.NeedToSync }}
        run: |
          echo ${{ env.RELEASE_NAME }}
          echo ${{ env.TAG_NAME }}

      - name: Checkout codebase
        if: ${{ env.NeedToSync }}
        uses: actions/checkout@v3

      - name: Setup Go
        if: ${{ env.NeedToSync }}
        uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod

      - name: Get dependencies and run
        if: ${{ env.NeedToSync }}
        run: |
          go run . -v 

      - name: Generate sha256 hash
        if: ${{ env.NeedToSync }}
        run: |
          sha256sum geosite.db > geosite.db.sha256sum

      - name: Release and upload assets
        if: ${{ env.NeedToSync }}
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          files: |
            geosite.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
